### ISSUE TITLE
No module named sets_ when running rd-start

### ISSUE THREAD

**Issue by soltysh** [python/docker-bpo#17]
@ezio-melotti I didn't notice this until now that I'm building the openshift version of bpo, when I run `rd-start` on a clean fresh repo clone I'm getting this. I didn't catch it earlier beacuse I had `sets_.pyc` in place, when I removed it I'm getting the exact same error. Looks like we need an update, any ideas?
```
tracker@ac87f66780bb:/$ rd-start
Traceback (most recent call last):
  File "/home/tracker/bin/roundup-server", line 11, in <module>
    run()
  File "/opt/tracker/roundup/roundup/scripts/roundup_server.py", line 978, in run
    httpd = config.get_server()
  File "/opt/tracker/roundup/roundup/scripts/roundup_server.py", line 633, in get_server
    for (name, home) in tracker_homes])
  File "/opt/tracker/roundup/roundup/instance.py", line 327, in open
    return Tracker(tracker_home, optimize=optimize)
  File "/opt/tracker/roundup/roundup/instance.py", line 102, in __init__
    self.detectors = self.get_extensions('detectors')
  File "/opt/tracker/roundup/roundup/instance.py", line 207, in get_extensions
    self._execfile(os.path.join(dirname, name), env)
  File "/opt/tracker/roundup/roundup/instance.py", line 239, in _execfile
    self._exec(self._compile(fname), env)
  File "/opt/tracker/roundup/roundup/instance.py", line 233, in _exec
    exec(obj, env)
  File "/opt/tracker/python-dev/detectors/autonosy.py", line 8, in <module>
    from roundup.anypy.sets_ import set
ImportError: No module named sets_
```

**Comment by zware** [comment]
A fresh run didn't reproduce this for me; perhaps it's been fixed in the interim?
